#https://oncletom.io/2016/travis-ssh-deploy/
language: node_js
node_js:
- 8.10.0
sudo: required
services:
- docker
cache:
  directories:
  - node_modules
addons:
  sshknownhosts:
  - andrewmarklloyd.com
branches:
  only:
  - master
script:
- ls -l
before_deploy:
- openssl aes-256-cbc -K $encrypted_03bc457d2f74_key -iv $encrypted_03bc457d2f74_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: scp deploy-ci.sh deploy@andrewmarklloyd.com:/tmp
  on:
    branch: master
