language: node_js
node_js:
- 8.10.0
sudo: required
services:
- docker
cache:
  directories:
  - node_modules
addons:
  sshknownhosts:
  - andrewmarklloyd.com
branches:
  only:
  - master
before_script:
- chmod 600 deploy && mv deploy ~/.ssh/idrsa
script:
- scp deploy-ci.sh deploy@andrewmarklloyd.com:/tmp
before_install:
- openssl aes-256-cbc -K $encrypted_03bc457d2f74_key -iv $encrypted_03bc457d2f74_iv
  -in deploy.enc -out deploy -d
