language: node_js
node_js:
  - "8.10.0"
sudo: required
services:
  - docker
cache:
  directories:
  - node_modules
addons:
  sshknownhosts:
  - andrewmarklloyd.com
branches:
  only:
    - master
before_script:
  - ls -al ~/.ssh
 #- cd front-end
 #- npm install
 #- cd ../

 
script:
  - ls -l
  #- ./build-ci.sh
