language: node_js
node_js:
  - "8.10.0"
sudo: required
services:
  - docker
cache:
  directories:
  - node_modules
addons:
  sshknownhosts:
  - andrewmarklloyd.com
branches:
  only:
    - master
before_script:
  - chmod 600 deploy && mv deploy ~/.ssh/idrsa
 #- cd front-end
 #- npm install
 #- cd ../

 
script:
  - ssh deploy@andrewmarklloyd.com 'ls -l'
  #- ./build-ci.sh
