version: '2'
services:
  spotify-app:
    image: andrewlloyd/spotify-playlist-app
    container_name: spotify-app
    restart: always
    ports:
      - "80:3000"
    env_file:
      - .env
    environment:
      - TEST=${TEST}
    depends_on:
      - db
  db:
    image: mysql:5.5
    restart: always
    environment:
      MYSQL_DATABASE: spotifyapi
      MYSQL_USER: spotifyapi
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
    - "3307:3306"
