version: '2'

services:
  db:
    image: mysql:5.5
    restart: always
    environment:
      MYSQL_DATABASE: spotifyapi
      MYSQL_USER: spotifyapi
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
    - "3307:3306"
